IMAGE_NAME = "geerlingguy/ubuntu1804"
CIDR_PREFIX = "10.10.10."

Vagrant.configure("2") do |config|
  vagrant_root = File.dirname(__FILE__)

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  (1..3).each do |i|
    config.vm.define "cass0#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: CIDR_PREFIX+"#{10+i}"
      node.vm.hostname = "cass0#{i}"
    end
  end
end
